######################################################################
#
# File name : comb_SA_tb_compile.do
# Created on: Fri Mar 13 10:50:19 +0800 2020
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../verilog" \
"comb_SA_tb_time_synth.v" \


quit -force

