######################################################################
#
# File name : comb_SA_tb_simulate.do
# Created on: Fri Mar 13 10:50:22 +0800 2020
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -L xil_defaultlib -L simprims_ver -L secureip -lib xil_defaultlib xil_defaultlib.comb_SA_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {comb_SA_tb_wave.do}

view wave
view structure
view signals

do {comb_SA_tb.udo}

run 1000ns
