# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param messaging.defaultLimit 2500
set_param simulator.modelsimInstallPath F:/modelsim64_10.1c/win64
set_msg_config -id {33-285} -limit 100
set_msg_config -id {33-288} -limit 100
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tsbv484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/ROLLO-I-Encrypt.cache/wt} [current_project]
set_property parent.project_path {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/ROLLO-I-Encrypt.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/ROLLO-I-Encrypt.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {{C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog}} [current_fileset]
read_verilog {
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/define.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/clog2.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/RNG/define.v}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/define.v}}]
set_property is_global_include true [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/define.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/clog2.v}}]
set_property is_global_include true [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/clog2.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/RNG/define.v}}]
read_verilog -library xil_defaultlib {
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/K_Gen_Ctrl.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/RegFiles.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/c_Gen_Ctrl.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/Gaussian Elimination/comb_SA.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/SHA3/f_permutation.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/RNG/f_permutation_200.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/GF2mZ Arithmetic/gf2m_mul.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/GF2mZ Arithmetic/gf2mz_top.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/SHA3/keccak.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/mem_dp.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/mem_sp.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/GF2mZ Arithmetic/mul_ctrl.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/Gaussian Elimination/node.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/SHA3/padder.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/RNG/prng.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/SHA3/rconst.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/RNG/rconst_200.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/SHA3/round.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/RNG/round_200.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/Verilog/encrypt_top.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/ROLLO-I-Encrypt.srcs/constrs_1/new/usr_constrain.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-I-Encrypt/ROLLO-I-Encrypt.srcs/constrs_1/new/usr_constrain.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top ROLLO_I_Encrypt -part xc7a200tsbv484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ROLLO_I_Encrypt.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ROLLO_I_Encrypt_utilization_synth.rpt -pb ROLLO_I_Encrypt_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
