######################################################################
#
# File name : decrypt_top_tb_wave.do
# Created on: Wed Sep 23 20:51:15 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
