######################################################################
#
# File name : decrypt_top_tb.udo
# Created on: Wed Sep 23 20:51:15 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
delete wave *
do {wave.do}