######################################################################
#
# File name : gf2mz_top_tb_simulate.do
# Created on: Mon Nov 30 15:50:20 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.gf2mz_top_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {gf2mz_top_tb_wave.do}

view wave
view structure
view signals

do {gf2mz_top_tb.udo}

run 1000ns
