######################################################################
#
# File name : gf2mz_top_tb.udo
# Created on: Tue Nov 05 15:38:49 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
