######################################################################
#
# File name : gf2mz_top_tb_compile.do
# Created on: Mon Nov 30 15:50:17 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../Improve-I.srcs/sources_1/new" \
"../../../../Improve-I.srcs/sources_1/new/gf2m_mul.v" \
"../../../../Improve-I.srcs/sources_1/new/gf2mz_top.v" \
"../../../../Improve-I.srcs/sources_1/new/mem_dp.v" \
"../../../../Improve-I.srcs/sources_1/new/mem_sp.v" \
"../../../../Improve-I.srcs/sources_1/new/mul_ctrl.v" \
"../../../../Improve-I.srcs/sources_1/new/gf2mz_top_tb.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

