######################################################################
#
# File name : keccak_tb_wave.do
# Created on: Wed Jan 08 15:46:52 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
