######################################################################
#
# File name : keccak_tb_compile.do
# Created on: Mon Sep 21 17:53:01 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../verilog" \
"../../../../../verilog/f_permutation.v" \
"../../../../../verilog/keccak.v" \
"../../../../../verilog/mem_sp.v" \
"../../../../../verilog/padder.v" \
"../../../../../verilog/rconst.v" \
"../../../../../verilog/round.v" \
"../../../../../verilog/keccak_tb.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

