######################################################################
#
# File name : decrypt_top_tb_wave.do
# Created on: Sun Dec 27 12:19:26 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
