onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /decrypt_top_tb/DUT/n
add wave -noupdate /decrypt_top_tb/DUT/m
add wave -noupdate /decrypt_top_tb/DUT/rd
add wave -noupdate /decrypt_top_tb/DUT/d
add wave -noupdate /decrypt_top_tb/DUT/WIDTH
add wave -noupdate /decrypt_top_tb/DUT/DEPTH
add wave -noupdate /decrypt_top_tb/DUT/DELAY_mul
add wave -noupdate /decrypt_top_tb/DUT/r
add wave -noupdate /decrypt_top_tb/DUT/x
add wave -noupdate /decrypt_top_tb/DUT/clk
add wave -noupdate /decrypt_top_tb/DUT/rst_b
add wave -noupdate /decrypt_top_tb/DUT/start
add wave -noupdate /decrypt_top_tb/DUT/finish
add wave -noupdate /decrypt_top_tb/DUT/data
add wave -noupdate /decrypt_top_tb/DUT/c_di
add wave -noupdate /decrypt_top_tb/DUT/c_do
add wave -noupdate /decrypt_top_tb/DUT/c_addr
add wave -noupdate /decrypt_top_tb/DUT/c_we
add wave -noupdate /decrypt_top_tb/DUT/x_dia
add wave -noupdate /decrypt_top_tb/DUT/x_doa
add wave -noupdate /decrypt_top_tb/DUT/x_dib
add wave -noupdate /decrypt_top_tb/DUT/x_dob
add wave -noupdate /decrypt_top_tb/DUT/x_addra
add wave -noupdate /decrypt_top_tb/DUT/x_addrb
add wave -noupdate /decrypt_top_tb/DUT/x_wea
add wave -noupdate /decrypt_top_tb/DUT/x_web
add wave -noupdate /decrypt_top_tb/DUT/S_di
add wave -noupdate /decrypt_top_tb/DUT/S_do
add wave -noupdate /decrypt_top_tb/DUT/S_addr
add wave -noupdate /decrypt_top_tb/DUT/S_we
add wave -noupdate /decrypt_top_tb/DUT/S1S2_doa
add wave -noupdate /decrypt_top_tb/DUT/S1S2_dob
add wave -noupdate /decrypt_top_tb/DUT/S1S2_dia
add wave -noupdate /decrypt_top_tb/DUT/S1S2_dib
add wave -noupdate /decrypt_top_tb/DUT/S1S2_addra
add wave -noupdate /decrypt_top_tb/DUT/S1S2_addrb
add wave -noupdate /decrypt_top_tb/DUT/S1S2_wea
add wave -noupdate /decrypt_top_tb/DUT/S1S2_web
add wave -noupdate /decrypt_top_tb/DUT/f_do
add wave -noupdate /decrypt_top_tb/DUT/f_addr
add wave -noupdate /decrypt_top_tb/DUT/f_we
add wave -noupdate /decrypt_top_tb/DUT/status
add wave -noupdate /decrypt_top_tb/DUT/gf2mz_start
add wave -noupdate /decrypt_top_tb/DUT/gf2mz_done
add wave -noupdate /decrypt_top_tb/DUT/gf2mz_S_addr
add wave -noupdate /decrypt_top_tb/DUT/gf2mz_S_we
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_start
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_done
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_S_addr
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_S_we
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_S1S2_addr
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_S1S2_di
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_S1S2_we
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_S_addr_reg
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen_S_we_reg
add wave -noupdate /decrypt_top_tb/DUT/RSR_start
add wave -noupdate /decrypt_top_tb/DUT/RSR_done
add wave -noupdate /decrypt_top_tb/DUT/RSR_S1S2_addra
add wave -noupdate /decrypt_top_tb/DUT/RSR_S1S2_addrb
add wave -noupdate /decrypt_top_tb/DUT/RSR_S1S2_dia
add wave -noupdate /decrypt_top_tb/DUT/RSR_S1S2_dib
add wave -noupdate /decrypt_top_tb/DUT/RSR_S1S2_wea
add wave -noupdate /decrypt_top_tb/DUT/RSR_S1S2_web
add wave -noupdate /decrypt_top_tb/DUT/sha3_start
add wave -noupdate /decrypt_top_tb/DUT/sha3_done
add wave -noupdate /decrypt_top_tb/DUT/sha3_mem_addr
add wave -noupdate /decrypt_top_tb/DUT/sha3_mem_we
add wave -noupdate /decrypt_top_tb/DUT/sha3_do
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/INIT
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/GF2MZ
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/S1S2GEN
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/RSR
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/SHA3
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/clk
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/rst_b
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/start
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/gf2mz_start
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/gf2mz_done
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/S1S2gen_start
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/S1S2gen_done
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/RSR_start
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/RSR_done
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/sha3_start
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/sha3_done
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/status
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/S1S2gen_done_reg
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/done
add wave -noupdate -radix unsigned /decrypt_top_tb/DUT/ctrl_top/state
add wave -noupdate /decrypt_top_tb/DUT/ctrl_top/next_state
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/WIDTH
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/DEPTH
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/FILE
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/clka
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/wea
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/ena
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/dia
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/addra
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/doa
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/clkb
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/web
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/enb
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/dib
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/addrb
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/dob
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/file
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/scan
add wave -noupdate /decrypt_top_tb/DUT/mem_S1S2/i
add wave -noupdate /decrypt_top_tb/DUT/RSR/DAT_W
add wave -noupdate /decrypt_top_tb/DUT/RSR/DAT_D
add wave -noupdate /decrypt_top_tb/DUT/RSR/d
add wave -noupdate /decrypt_top_tb/DUT/RSR/clk
add wave -noupdate /decrypt_top_tb/DUT/RSR/rst_b
add wave -noupdate /decrypt_top_tb/DUT/RSR/start
add wave -noupdate /decrypt_top_tb/DUT/RSR/mat_sel
add wave -noupdate /decrypt_top_tb/DUT/RSR/is_last
add wave -noupdate /decrypt_top_tb/DUT/RSR/finish
add wave -noupdate /decrypt_top_tb/DUT/RSR/mem_dina
add wave -noupdate /decrypt_top_tb/DUT/RSR/mem_douta
add wave -noupdate /decrypt_top_tb/DUT/RSR/mem_doutb
add wave -noupdate /decrypt_top_tb/DUT/RSR/mem_addra
add wave -noupdate /decrypt_top_tb/DUT/RSR/mem_addrb
add wave -noupdate /decrypt_top_tb/DUT/RSR/mem_rwa
add wave -noupdate /decrypt_top_tb/DUT/RSR/mem_rwb
add wave -noupdate /decrypt_top_tb/DUT/RSR/SA_mode
add wave -noupdate /decrypt_top_tb/DUT/RSR/SA_start
add wave -noupdate /decrypt_top_tb/DUT/RSR/SA_swap
add wave -noupdate /decrypt_top_tb/DUT/RSR/SA_din
add wave -noupdate /decrypt_top_tb/DUT/RSR/SA_dout
add wave -noupdate /decrypt_top_tb/DUT/RSR/ctrl_mem_doutb
add wave -noupdate /decrypt_top_tb/DUT/RSR/ctrl_wr_en
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/k
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/k1
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/l
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/d
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/READ_DELAY
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/ls2
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/rd
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/INIT
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/TRI
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/TRANSITION
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/SYS_READ
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/SYS_SWAP
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/SYS_WRITE
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/MEM_WRITE
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/clk
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/rst_b
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/start
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/mat_sel
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/is_last
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/done
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/SA_mode
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/SA_start
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/SA_swap
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/SA_din
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/mem_dina
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/mem_doutb
add wave -noupdate -itemcolor Blue -radix unsigned /decrypt_top_tb/DUT/RSR/CTRL/mem_addra
add wave -noupdate -itemcolor Blue -radix unsigned /decrypt_top_tb/DUT/RSR/CTRL/mem_addrb
add wave -noupdate -itemcolor Blue -radix unsigned /decrypt_top_tb/DUT/RSR/CTRL/mem_rwa
add wave -noupdate -itemcolor Blue -radix unsigned /decrypt_top_tb/DUT/RSR/CTRL/mem_rwb
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/mem_wr_en
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/tri_done
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/sys_read_done
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/sys_swap_done
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/sys_write_done
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/mem_write_done
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/cnt
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/round
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/round_d
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/reg_k
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/first_half_lock
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/second_half_lock
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/first_half_except
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/second_half_except
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/first_half_reg
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/second_half_reg
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/first_half
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/second_half
add wave -noupdate -radix unsigned /decrypt_top_tb/DUT/RSR/CTRL/min_addr
add wave -noupdate -radix unsigned /decrypt_top_tb/DUT/RSR/CTRL/max_addr
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/intersect_num
add wave -noupdate -color Yellow -radix unsigned /decrypt_top_tb/DUT/RSR/CTRL/state
add wave -noupdate /decrypt_top_tb/DUT/RSR/CTRL/next_state
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/n
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/m
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/rd
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/d
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/iter
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/WIDTH
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/DEPTH
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/DELAY_mul
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/DELAY_rd
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/INIT
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/PRE
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/MUL
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/POST
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/clk
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/rst_b
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/start
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/iterate
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/finish
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/S_din
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/S_addr
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/S_rw
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/f_din
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/f_addr
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/f_rw
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/S1S2_dout
add wave -noupdate -radix unsigned /decrypt_top_tb/DUT/S1S2gen/S1S2_addr
add wave -noupdate -radix unsigned /decrypt_top_tb/DUT/S1S2gen/S1S2_rw
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/mul_start
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/mul_done
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/mul_op_a
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/mul_op_b
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/mul_op_c
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/cnt
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/idx
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/mode
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/shift_reg
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/PRE_done
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/MUL_done
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/POST_done
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/done
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/state
add wave -noupdate /decrypt_top_tb/DUT/S1S2gen/next_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {RSR_start {38070000 ps} 0} {RSR_end {67592030 ps} 0} {S1S2gen_start {67722027 ps} 0}
quietly wave cursor active 3
configure wave -namecolwidth 361
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {67692153 ps} {67747847 ps}
