######################################################################
#
# File name : S1S2_gen_tb.udo
# Created on: Fri Sep 11 11:52:21 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
delete wave *
do {wave.do}