######################################################################
#
# File name : S1S2_gen_tb_simulate.do
# Created on: Mon Sep 14 16:17:35 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.S1S2_gen_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {S1S2_gen_tb_wave.do}

view wave
view structure
view signals

do {S1S2_gen_tb.udo}

run 1000ns
