######################################################################
#
# File name : encrypt_top_tb_wave.do
# Created on: Thu Apr 09 19:58:29 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
