######################################################################
#
# File name : gs_elim_top_tb_compile.do
# Created on: Thu Dec 24 10:25:52 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib "C:/Users/David/Dropbox/ROLLO/hardware/Gaussian_Elimination_for_Decryption/Verilog_thin/define.v" "C:/Users/David/Dropbox/ROLLO/hardware/Gaussian_Elimination_for_Decryption/Verilog_thin/clog2.v" "+incdir+../../../../Verilog_thin" \
"../../../../Verilog_thin/comb_SA.v" \
"../../../../Verilog_thin/gs_elim_ctrl-thin.v" \
"../../../../Verilog_thin/gs_elim_top.v" \
"../../../../Verilog_thin/mem_dp.v" \
"../../../../Verilog_thin/node.v" \
"../../../../Verilog_thin/gs_elim_top_tb.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

