######################################################################
#
# File name : gs_elim_top_tb_simulate.do
# Created on: Thu Dec 24 10:25:57 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.gs_elim_top_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {gs_elim_top_tb_wave.do}

view wave
view structure
view signals

do {gs_elim_top_tb.udo}

run 1000ns
