######################################################################
#
# File name : gs_elim_top_tb_wave.do
# Created on: Wed Dec 23 13:59:04 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
