######################################################################
#
# File name : gs_elim_top_tb.udo
# Created on: Wed Dec 23 13:59:04 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
delete wave *
do {wave.do}
