######################################################################
#
# File name : S1S2_gen_tb_compile.do
# Created on: Mon Sep 14 16:17:31 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../Verilog" \
"../../../../Verilog/S1S2_gen.v" \
"../../../../Verilog/gf2m_mul.v" \
"../../../../Verilog/mul_ctrl.v" \
"../../../../Verilog/gf2mz_top_tb.v" \
"../../../../Verilog/gf2mz_top.v" \
"../../../../Verilog/mem_dp.v" \
"../../../../Verilog/mem_sp.v" \
"../../../../Verilog/S1S2_gen_tb.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

