onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /S1S2_gen_tb/m
add wave -noupdate /S1S2_gen_tb/n
add wave -noupdate /S1S2_gen_tb/d
add wave -noupdate /S1S2_gen_tb/WIDTH
add wave -noupdate /S1S2_gen_tb/DEPTH
add wave -noupdate /S1S2_gen_tb/clk
add wave -noupdate /S1S2_gen_tb/start
add wave -noupdate /S1S2_gen_tb/rst_b
add wave -noupdate /S1S2_gen_tb/finish
add wave -noupdate /S1S2_gen_tb/S_dout
add wave -noupdate /S1S2_gen_tb/S_addr
add wave -noupdate /S1S2_gen_tb/S_rw
add wave -noupdate /S1S2_gen_tb/f_dout
add wave -noupdate /S1S2_gen_tb/f_addr
add wave -noupdate /S1S2_gen_tb/f_rw
add wave -noupdate /S1S2_gen_tb/S1S2_din
add wave -noupdate /S1S2_gen_tb/S1S2_addr
add wave -noupdate /S1S2_gen_tb/S1S2_rw
add wave -noupdate /S1S2_gen_tb/S_rw
add wave -noupdate /S1S2_gen_tb/f_addr
add wave -noupdate /S1S2_gen_tb/f_rw
add wave -noupdate /S1S2_gen_tb/S1S2_rw
add wave -noupdate /S1S2_gen_tb/i
add wave -noupdate /S1S2_gen_tb/start_time
add wave -noupdate /S1S2_gen_tb/end_time
add wave -noupdate /S1S2_gen_tb/scan_file
add wave -noupdate /S1S2_gen_tb/DUT/n
add wave -noupdate /S1S2_gen_tb/DUT/m
add wave -noupdate /S1S2_gen_tb/DUT/d
add wave -noupdate /S1S2_gen_tb/DUT/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/DEPTH
add wave -noupdate /S1S2_gen_tb/DUT/DELAY_mul
add wave -noupdate /S1S2_gen_tb/DUT/DELAY_rd
add wave -noupdate /S1S2_gen_tb/DUT/INIT
add wave -noupdate /S1S2_gen_tb/DUT/PRE
add wave -noupdate /S1S2_gen_tb/DUT/MUL
add wave -noupdate /S1S2_gen_tb/DUT/POST
add wave -noupdate /S1S2_gen_tb/DUT/clk
add wave -noupdate /S1S2_gen_tb/DUT/rst_b
add wave -noupdate /S1S2_gen_tb/DUT/start
add wave -noupdate /S1S2_gen_tb/DUT/finish
add wave -noupdate -itemcolor {Lime Green} /S1S2_gen_tb/DUT/S_din
add wave -noupdate -itemcolor {Lime Green} -radix unsigned /S1S2_gen_tb/DUT/S_addr
add wave -noupdate -itemcolor {Lime Green} /S1S2_gen_tb/DUT/S_rw
add wave -noupdate -itemcolor Blue /S1S2_gen_tb/DUT/f_din
add wave -noupdate -itemcolor Blue /S1S2_gen_tb/DUT/f_addr
add wave -noupdate -itemcolor Blue /S1S2_gen_tb/DUT/f_rw
add wave -noupdate -itemcolor Cyan /S1S2_gen_tb/DUT/S1S2_dout
add wave -noupdate -itemcolor Cyan -radix unsigned /S1S2_gen_tb/DUT/S1S2_addr
add wave -noupdate -itemcolor Cyan /S1S2_gen_tb/DUT/S1S2_rw
add wave -noupdate /S1S2_gen_tb/DUT/mul_start
add wave -noupdate /S1S2_gen_tb/DUT/mul_done
add wave -noupdate /S1S2_gen_tb/DUT/mul_op_a
add wave -noupdate /S1S2_gen_tb/DUT/mul_op_b
add wave -noupdate /S1S2_gen_tb/DUT/mul_op_c
add wave -noupdate -color Cyan -radix unsigned /S1S2_gen_tb/DUT/cnt
add wave -noupdate -itemcolor Red -radix unsigned /S1S2_gen_tb/DUT/idx
add wave -noupdate /S1S2_gen_tb/DUT/mode
add wave -noupdate /S1S2_gen_tb/DUT/shift_reg
add wave -noupdate /S1S2_gen_tb/DUT/PRE_done
add wave -noupdate /S1S2_gen_tb/DUT/MUL_done
add wave -noupdate /S1S2_gen_tb/DUT/POST_done
add wave -noupdate /S1S2_gen_tb/DUT/done
add wave -noupdate -color Gold -radix unsigned /S1S2_gen_tb/DUT/state
add wave -noupdate /S1S2_gen_tb/DUT/next_state
add wave -noupdate /S1S2_gen_tb/DUT/mul/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/d
add wave -noupdate /S1S2_gen_tb/DUT/mul/DIGIT_N
add wave -noupdate /S1S2_gen_tb/DUT/mul/WIDTH_A
add wave -noupdate /S1S2_gen_tb/DUT/mul/clk
add wave -noupdate /S1S2_gen_tb/DUT/mul/rst_b
add wave -noupdate /S1S2_gen_tb/DUT/mul/start
add wave -noupdate /S1S2_gen_tb/DUT/mul/op_a
add wave -noupdate /S1S2_gen_tb/DUT/mul/op_b
add wave -noupdate /S1S2_gen_tb/DUT/mul/done
add wave -noupdate /S1S2_gen_tb/DUT/mul/op_c
add wave -noupdate /S1S2_gen_tb/DUT/mul/cx1
add wave -noupdate /S1S2_gen_tb/DUT/mul/cx
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx0
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx1
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx2
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx3
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx4
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx5
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx6
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx7
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx8
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx9
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx10
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx11
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx12
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx13
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx14
add wave -noupdate /S1S2_gen_tb/DUT/mul/bx15
add wave -noupdate /S1S2_gen_tb/DUT/mul/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/b
add wave -noupdate /S1S2_gen_tb/DUT/mul/c
add wave -noupdate /S1S2_gen_tb/DUT/mul/start_en
add wave -noupdate /S1S2_gen_tb/DUT/mul/cnt
add wave -noupdate /S1S2_gen_tb/DUT/mul/op_a_BigEndian
add wave -noupdate /S1S2_gen_tb/DUT/mul/op_b_BigEndian
add wave -noupdate /S1S2_gen_tb/DUT/mul/op_c_BigEndian
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[78]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[77]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[76]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[75]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[74]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[73]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[72]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[71]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[70]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[69]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[68]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[67]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[66]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[65]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[64]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[63]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[62]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[61]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[60]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[59]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[58]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[57]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[56]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[55]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[54]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[53]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[52]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[51]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[50]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[49]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[48]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[47]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[46]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[45]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[44]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[43]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[42]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[41]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[40]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[39]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[38]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[37]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[36]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[35]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[34]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[33]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[32]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[31]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[30]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[29]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[28]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[27]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[26]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[25]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[24]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[23]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[22]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[21]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[20]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[19]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[18]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[17]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[16]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[15]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[14]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[13]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[12]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[11]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[10]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[9]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[8]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[7]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[6]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[5]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[4]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[3]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[2]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[1]/w}
add wave -noupdate {/S1S2_gen_tb/DUT/mul/L0[0]/w}
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_1/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_1/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_1/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_1/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_1/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_1/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_1/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_2/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_2/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_2/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_2/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_2/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_2/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_2/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_3/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_3/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_3/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_3/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_3/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_3/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_3/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_4/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_4/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_4/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_4/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_4/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_4/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_4/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_5/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_5/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_5/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_5/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_5/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_5/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_5/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_6/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_6/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_6/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_6/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_6/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_6/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_6/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_7/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_7/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_7/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_7/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_7/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_7/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_7/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_8/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_8/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_8/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_8/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_8/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_8/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_8/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_9/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_9/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_9/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_9/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_9/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_9/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_9/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_10/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_10/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_10/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_10/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_10/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_10/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_10/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_11/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_11/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_11/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_11/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_11/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_11/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_11/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_12/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_12/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_12/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_12/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_12/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_12/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_12/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_13/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_13/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_13/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_13/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_13/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_13/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_13/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_14/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_14/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_14/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_14/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_14/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_14/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_14/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_15/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_15/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_15/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_15/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_15/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_15/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_15/px1
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_16/WIDTH
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_16/k
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_16/i
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_16/a
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_16/p
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_16/px
add wave -noupdate /S1S2_gen_tb/DUT/mul/shift_16/px1
add wave -noupdate /S1S2_gen_tb/mem_S/WIDTH
add wave -noupdate /S1S2_gen_tb/mem_S/DEPTH
add wave -noupdate /S1S2_gen_tb/mem_S/FILE
add wave -noupdate /S1S2_gen_tb/mem_S/clk
add wave -noupdate /S1S2_gen_tb/mem_S/di
add wave -noupdate /S1S2_gen_tb/mem_S/addr
add wave -noupdate /S1S2_gen_tb/mem_S/en
add wave -noupdate /S1S2_gen_tb/mem_S/we
add wave -noupdate /S1S2_gen_tb/mem_S/do
add wave -noupdate /S1S2_gen_tb/mem_S/file
add wave -noupdate /S1S2_gen_tb/mem_S/scan
add wave -noupdate /S1S2_gen_tb/mem_S/i
add wave -noupdate /S1S2_gen_tb/mem_f/WIDTH
add wave -noupdate /S1S2_gen_tb/mem_f/DEPTH
add wave -noupdate /S1S2_gen_tb/mem_f/FILE
add wave -noupdate /S1S2_gen_tb/mem_f/clk
add wave -noupdate /S1S2_gen_tb/mem_f/di
add wave -noupdate /S1S2_gen_tb/mem_f/addr
add wave -noupdate /S1S2_gen_tb/mem_f/en
add wave -noupdate /S1S2_gen_tb/mem_f/we
add wave -noupdate /S1S2_gen_tb/mem_f/do
add wave -noupdate /S1S2_gen_tb/mem_f/file
add wave -noupdate /S1S2_gen_tb/mem_f/scan
add wave -noupdate /S1S2_gen_tb/mem_f/i
add wave -noupdate /S1S2_gen_tb/mem_S1S2/WIDTH
add wave -noupdate /S1S2_gen_tb/mem_S1S2/DEPTH
add wave -noupdate /S1S2_gen_tb/mem_S1S2/FILE
add wave -noupdate /S1S2_gen_tb/mem_S1S2/clk
add wave -noupdate /S1S2_gen_tb/mem_S1S2/di
add wave -noupdate /S1S2_gen_tb/mem_S1S2/addr
add wave -noupdate /S1S2_gen_tb/mem_S1S2/en
add wave -noupdate /S1S2_gen_tb/mem_S1S2/we
add wave -noupdate /S1S2_gen_tb/mem_S1S2/do
add wave -noupdate /S1S2_gen_tb/mem_S1S2/file
add wave -noupdate /S1S2_gen_tb/mem_S1S2/scan
add wave -noupdate /S1S2_gen_tb/mem_S1S2/i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {PRE {30035 ps} 0} {MUL {59873 ps} 0} {POST {70067 ps} 0} {S1_to_S2 {3820198 ps} 0} {{Cursor 5} {7609936 ps} 0}
quietly wave cursor active 5
configure wave -namecolwidth 354
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {7528710 ps} {7681290 ps}
