# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath F:/modelsim64_10.1c/win64
create_project -in_memory -part xc7a15tcsg325-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/Gaussian_Elimination.cache/wt} [current_project]
set_property parent.project_path {C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/Gaussian_Elimination.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/Gaussian_Elimination.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  {C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/verilog/clog2.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/verilog/define.v}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/verilog/clog2.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/verilog/define.v}}]
read_verilog -library xil_defaultlib {
  {C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/verilog/node.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/verilog/comb_SA.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/verilog/mem.v}
  {C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/verilog/comb_SA_tb.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/Gaussian_Elimination.srcs/constrs_1/new/usr_constrain.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/David/Dropbox/LRPC Code/hardware/Gaussian_Elimination/Gaussian_Elimination.srcs/constrs_1/new/usr_constrain.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top comb_SA -part xc7a15tcsg325-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef comb_SA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file comb_SA_utilization_synth.rpt -pb comb_SA_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
