######################################################################
#
# File name : encrypt_top_tb.udo
# Created on: Thu Apr 09 19:58:29 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
delete wave *
delete wave /glbl/GSR

do {wave.do}
