######################################################################
#
# File name : encrypt_top_tb_compile.do
# Created on: Fri May 15 10:38:41 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib "C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-II-Encrypt/Verilog/define.v" "C:/Users/David/Dropbox/LRPC Code/hardware/ROLLO Encrypt/ROLLO-II-Encrypt/Verilog/clog2.v" \
"../../../../Verilog/define.v" \
"../../../../Verilog/clog2.v" \
"../../../../Verilog/K_Gen_Ctrl.v" \
"../../../../Verilog/RegFiles.v" \
"../../../../Verilog/c_Gen_Ctrl.v" \
"../../../../Verilog/Gaussian Elimination/comb_SA.v" \
"../../../../Verilog/encrypt_top.v" \
"../../../../Verilog/SHA3/f_permutation.v" \
"../../../../Verilog/RNG/f_permutation_200.v" \
"../../../../Verilog/GF2mZ Arithmetic/gf2m_mul.v" \
"../../../../Verilog/GF2mZ Arithmetic/gf2mz_top.v" \
"../../../../Verilog/SHA3/keccak.v" \
"../../../../Verilog/mem_dp.v" \
"../../../../Verilog/mem_sp.v" \
"../../../../Verilog/GF2mZ Arithmetic/mul_ctrl.v" \
"../../../../Verilog/Gaussian Elimination/node.v" \
"../../../../Verilog/SHA3/padder.v" \
"../../../../Verilog/RNG/prng.v" \
"../../../../Verilog/SHA3/rconst.v" \
"../../../../Verilog/RNG/rconst_200.v" \
"../../../../Verilog/SHA3/round.v" \
"../../../../Verilog/RNG/round_200.v" \
"../../../../Verilog/encrypt_top_tb.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

