######################################################################
#
# File name : comb_SA_tb_simulate.do
# Created on: Fri Mar 13 10:53:02 +0800 2020
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L secureip -lib xil_defaultlib xil_defaultlib.comb_SA_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {comb_SA_tb_wave.do}

view wave
view structure
view signals

do {comb_SA_tb.udo}

run 1000ns
