######################################################################
#
# File name : comb_SA_tb_wave.do
# Created on: Fri Mar 13 10:49:09 +0800 2020
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
