######################################################################
#
# File name : GF2m_mul_simulate.do
# Created on: Tue Aug 13 19:14:51 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.GF2m_mul xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {GF2m_mul_wave.do}

view wave
view structure
view signals

do {GF2m_mul.udo}

run 1000ns
