######################################################################
#
# File name : GF2m_mul_tb_wave.do
# Created on: Tue Aug 13 19:42:49 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
