######################################################################
#
# File name : GF2m_mul_penta_tb_compile.do
# Created on: Thu Aug 22 19:18:52 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../GF2m_multiplier.srcs/sources_1/new/GF2m_mul_penta.v" \
"../../../../GF2m_multiplier.srcs/sources_1/new/GF2m_mul_penta_tb.v" \


# compile glbl module
F:\\modelsim64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

