######################################################################
#
# File name : GF2m_mul_penta_tb_wave.do
# Created on: Thu Aug 22 19:18:54 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
