######################################################################
#
# File name : decrypt_top_tb.udo
# Created on: Mon Sep 28 11:50:25 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
delete wave *
do {wave.do}
