######################################################################
#
# File name : decrypt_top_tb_wave.do
# Created on: Mon Sep 28 11:50:25 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
