######################################################################
#
# File name : encrypt_top_tb_wave.do
# Created on: Sun May 10 12:16:07 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
