onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/clk
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/start
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/rst_b
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/done
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/rng_data
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/rng_finish
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/rng_start
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/rng_seed
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/rng_in_mod
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_data_in
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_rw
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_ctrl_w
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_addr
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_data_out
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/GS_finish
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/GS_full_rank
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/GS_data_in
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/GS_mode
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/GS_start
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/GS_data_out
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_rref_data_in
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_rref_rw
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_rref_addr
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_rref_data_out
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/sha3_finish
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/sha3_mem_addr
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/sha3_mem_rw
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/sha3_mem_dout
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/sha3_start
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/c_gen_start
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_done
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/GS_done
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_rref_done
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/SHA3_done
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/GS_start_tmp
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/E_addr_tmp
add wave -noupdate -color Gold -radix unsigned -radixshowbase 0 /encrypt_top_tb/DUT/K_Gen_Ctrl/state
add wave -noupdate /encrypt_top_tb/DUT/K_Gen_Ctrl/next_state
add wave -noupdate /encrypt_top_tb/DUT/SHA3/clk
add wave -noupdate /encrypt_top_tb/DUT/SHA3/rst_b
add wave -noupdate /encrypt_top_tb/DUT/SHA3/in_ready
add wave -noupdate /encrypt_top_tb/DUT/SHA3/mem_din
add wave -noupdate /encrypt_top_tb/DUT/SHA3/mem_rw
add wave -noupdate /encrypt_top_tb/DUT/SHA3/mem_addr
add wave -noupdate /encrypt_top_tb/DUT/SHA3/out_usr
add wave -noupdate /encrypt_top_tb/DUT/SHA3/out_ready
add wave -noupdate /encrypt_top_tb/DUT/SHA3/pad_start
add wave -noupdate /encrypt_top_tb/DUT/SHA3/pad_start_tmp
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_out
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_out1
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_out_ready
add wave -noupdate /encrypt_top_tb/DUT/SHA3/is_last
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_ack
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_out
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_out_ready
add wave -noupdate /encrypt_top_tb/DUT/SHA3/i
add wave -noupdate /encrypt_top_tb/DUT/SHA3/out
add wave -noupdate /encrypt_top_tb/DUT/SHA3/out1
add wave -noupdate /encrypt_top_tb/DUT/SHA3/E_addr
add wave -noupdate /encrypt_top_tb/DUT/SHA3/E_do
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/clk
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/rst_b
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/in
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/in_ready
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/is_last
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/out
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/out_ready
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/v1
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/in1
add wave -noupdate /encrypt_top_tb/DUT/SHA3/padder_/tmp
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/clk
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/rst_b
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/in
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/in_ready
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/ack
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/out
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/out_ready
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/i
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_in
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_out
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/rc
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/update
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/accept
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/calc
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/rconst_/i
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/rconst_/rc
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/in
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/round_const
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/out
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/a
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/b
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/c
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/d
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/e
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/f
add wave -noupdate /encrypt_top_tb/DUT/SHA3/f_permutation_/round_/g
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5318933 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 465
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {5294535 ps} {5465879 ps}
