######################################################################
#
# File name : comb_SA_wave.do
# Created on: Wed Mar 11 11:03:56 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
