######################################################################
#
# File name : comb_SA_tb_wave.do
# Created on: Wed Mar 11 15:19:54 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
