######################################################################
#
# File name : comb_SA_tb_compile.do
# Created on: Wed Mar 18 15:14:28 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../verilog" \
"../../../../verilog/node.v" \
"../../../../verilog/comb_SA.v" \
"../../../../verilog/mem.v" \
"../../../../verilog/comb_SA_tb.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

