onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /comb_SA_tb/clk
add wave -noupdate /comb_SA_tb/rst_b
add wave -noupdate /comb_SA_tb/start
add wave -noupdate /comb_SA_tb/data
add wave -noupdate -radix unsigned /comb_SA_tb/addr
add wave -noupdate /comb_SA_tb/finish
add wave -noupdate /comb_SA_tb/r_A_and
add wave -noupdate /comb_SA_tb/q
add wave -noupdate /comb_SA_tb/i
add wave -noupdate /comb_SA_tb/start_time
add wave -noupdate /comb_SA_tb/DUT/clk
add wave -noupdate /comb_SA_tb/DUT/rst_b
add wave -noupdate /comb_SA_tb/DUT/start
add wave -noupdate /comb_SA_tb/DUT/data
add wave -noupdate /comb_SA_tb/DUT/finish
add wave -noupdate /comb_SA_tb/DUT/r_A_and
add wave -noupdate /comb_SA_tb/DUT/start_tmp
add wave -noupdate /comb_SA_tb/DUT/start_row
add wave -noupdate /comb_SA_tb/DUT/start_in_0_0
add wave -noupdate /comb_SA_tb/DUT/start_out_0_0
add wave -noupdate /comb_SA_tb/DUT/op_out_0_0
add wave -noupdate /comb_SA_tb/DUT/r_0_0
add wave -noupdate /comb_SA_tb/DUT/data_in_0_0
add wave -noupdate /comb_SA_tb/DUT/data_out_0_0
add wave -noupdate /comb_SA_tb/DUT/start_in_0_1
add wave -noupdate /comb_SA_tb/DUT/start_out_0_1
add wave -noupdate /comb_SA_tb/DUT/op_in_0_1
add wave -noupdate /comb_SA_tb/DUT/op_out_0_1
add wave -noupdate /comb_SA_tb/DUT/data_in_0_1
add wave -noupdate /comb_SA_tb/DUT/data_out_0_1
add wave -noupdate /comb_SA_tb/DUT/start_in_0_2
add wave -noupdate /comb_SA_tb/DUT/start_out_0_2
add wave -noupdate /comb_SA_tb/DUT/op_in_0_2
add wave -noupdate /comb_SA_tb/DUT/op_out_0_2
add wave -noupdate /comb_SA_tb/DUT/data_in_0_2
add wave -noupdate /comb_SA_tb/DUT/data_out_0_2
add wave -noupdate /comb_SA_tb/DUT/start_in_0_3
add wave -noupdate /comb_SA_tb/DUT/start_out_0_3
add wave -noupdate /comb_SA_tb/DUT/op_in_0_3
add wave -noupdate /comb_SA_tb/DUT/op_out_0_3
add wave -noupdate /comb_SA_tb/DUT/data_in_0_3
add wave -noupdate /comb_SA_tb/DUT/data_out_0_3
add wave -noupdate /comb_SA_tb/DUT/start_in_1_1
add wave -noupdate /comb_SA_tb/DUT/start_out_1_1
add wave -noupdate /comb_SA_tb/DUT/op_out_1_1
add wave -noupdate /comb_SA_tb/DUT/r_1_1
add wave -noupdate /comb_SA_tb/DUT/data_in_1_1
add wave -noupdate /comb_SA_tb/DUT/data_out_1_1
add wave -noupdate /comb_SA_tb/DUT/start_in_1_2
add wave -noupdate /comb_SA_tb/DUT/start_out_1_2
add wave -noupdate /comb_SA_tb/DUT/op_in_1_2
add wave -noupdate /comb_SA_tb/DUT/op_out_1_2
add wave -noupdate /comb_SA_tb/DUT/data_in_1_2
add wave -noupdate /comb_SA_tb/DUT/data_out_1_2
add wave -noupdate /comb_SA_tb/DUT/start_in_1_3
add wave -noupdate /comb_SA_tb/DUT/start_out_1_3
add wave -noupdate /comb_SA_tb/DUT/op_in_1_3
add wave -noupdate /comb_SA_tb/DUT/op_out_1_3
add wave -noupdate /comb_SA_tb/DUT/data_in_1_3
add wave -noupdate /comb_SA_tb/DUT/data_out_1_3
add wave -noupdate /comb_SA_tb/DUT/start_in_2_2
add wave -noupdate /comb_SA_tb/DUT/start_out_2_2
add wave -noupdate /comb_SA_tb/DUT/op_out_2_2
add wave -noupdate /comb_SA_tb/DUT/r_2_2
add wave -noupdate /comb_SA_tb/DUT/data_in_2_2
add wave -noupdate /comb_SA_tb/DUT/data_out_2_2
add wave -noupdate /comb_SA_tb/DUT/start_in_2_3
add wave -noupdate /comb_SA_tb/DUT/start_out_2_3
add wave -noupdate /comb_SA_tb/DUT/op_in_2_3
add wave -noupdate /comb_SA_tb/DUT/op_out_2_3
add wave -noupdate /comb_SA_tb/DUT/data_in_2_3
add wave -noupdate /comb_SA_tb/DUT/data_out_2_3
add wave -noupdate /comb_SA_tb/DUT/A_0_0/clk
add wave -noupdate /comb_SA_tb/DUT/A_0_0/rst_b
add wave -noupdate /comb_SA_tb/DUT/A_0_0/data_in
add wave -noupdate /comb_SA_tb/DUT/A_0_0/start_in
add wave -noupdate /comb_SA_tb/DUT/A_0_0/op_out
add wave -noupdate /comb_SA_tb/DUT/A_0_0/start_out
add wave -noupdate /comb_SA_tb/DUT/A_0_0/data_out
add wave -noupdate -itemcolor Gold /comb_SA_tb/DUT/A_0_0/r
add wave -noupdate /comb_SA_tb/DUT/A_0_0/r_reg
add wave -noupdate /comb_SA_tb/DUT/B_0_1/clk
add wave -noupdate /comb_SA_tb/DUT/B_0_1/rst_b
add wave -noupdate /comb_SA_tb/DUT/B_0_1/data_in
add wave -noupdate /comb_SA_tb/DUT/B_0_1/start_in
add wave -noupdate /comb_SA_tb/DUT/B_0_1/op_in
add wave -noupdate /comb_SA_tb/DUT/B_0_1/op_out
add wave -noupdate /comb_SA_tb/DUT/B_0_1/start_out
add wave -noupdate /comb_SA_tb/DUT/B_0_1/data_out
add wave -noupdate -itemcolor Gold /comb_SA_tb/DUT/B_0_1/r
add wave -noupdate /comb_SA_tb/DUT/B_0_1/r_reg
add wave -noupdate /comb_SA_tb/DUT/B_0_2/clk
add wave -noupdate /comb_SA_tb/DUT/B_0_2/rst_b
add wave -noupdate /comb_SA_tb/DUT/B_0_2/data_in
add wave -noupdate /comb_SA_tb/DUT/B_0_2/start_in
add wave -noupdate /comb_SA_tb/DUT/B_0_2/op_in
add wave -noupdate /comb_SA_tb/DUT/B_0_2/op_out
add wave -noupdate /comb_SA_tb/DUT/B_0_2/start_out
add wave -noupdate /comb_SA_tb/DUT/B_0_2/data_out
add wave -noupdate -itemcolor Gold /comb_SA_tb/DUT/B_0_2/r
add wave -noupdate /comb_SA_tb/DUT/B_0_2/r_reg
add wave -noupdate /comb_SA_tb/DUT/B_0_3/clk
add wave -noupdate /comb_SA_tb/DUT/B_0_3/rst_b
add wave -noupdate /comb_SA_tb/DUT/B_0_3/data_in
add wave -noupdate /comb_SA_tb/DUT/B_0_3/start_in
add wave -noupdate /comb_SA_tb/DUT/B_0_3/op_in
add wave -noupdate /comb_SA_tb/DUT/B_0_3/op_out
add wave -noupdate /comb_SA_tb/DUT/B_0_3/start_out
add wave -noupdate /comb_SA_tb/DUT/B_0_3/data_out
add wave -noupdate -itemcolor Gold /comb_SA_tb/DUT/B_0_3/r
add wave -noupdate /comb_SA_tb/DUT/B_0_3/r_reg
add wave -noupdate /comb_SA_tb/DUT/A_1_1/clk
add wave -noupdate /comb_SA_tb/DUT/A_1_1/rst_b
add wave -noupdate /comb_SA_tb/DUT/A_1_1/data_in
add wave -noupdate /comb_SA_tb/DUT/A_1_1/start_in
add wave -noupdate /comb_SA_tb/DUT/A_1_1/op_out
add wave -noupdate /comb_SA_tb/DUT/A_1_1/start_out
add wave -noupdate /comb_SA_tb/DUT/A_1_1/data_out
add wave -noupdate -itemcolor Green /comb_SA_tb/DUT/A_1_1/r
add wave -noupdate /comb_SA_tb/DUT/A_1_1/r_reg
add wave -noupdate /comb_SA_tb/DUT/B_1_2/clk
add wave -noupdate /comb_SA_tb/DUT/B_1_2/rst_b
add wave -noupdate /comb_SA_tb/DUT/B_1_2/data_in
add wave -noupdate /comb_SA_tb/DUT/B_1_2/start_in
add wave -noupdate /comb_SA_tb/DUT/B_1_2/op_in
add wave -noupdate /comb_SA_tb/DUT/B_1_2/op_out
add wave -noupdate /comb_SA_tb/DUT/B_1_2/start_out
add wave -noupdate /comb_SA_tb/DUT/B_1_2/data_out
add wave -noupdate -itemcolor Green /comb_SA_tb/DUT/B_1_2/r
add wave -noupdate /comb_SA_tb/DUT/B_1_2/r_reg
add wave -noupdate /comb_SA_tb/DUT/B_1_3/clk
add wave -noupdate /comb_SA_tb/DUT/B_1_3/rst_b
add wave -noupdate /comb_SA_tb/DUT/B_1_3/data_in
add wave -noupdate /comb_SA_tb/DUT/B_1_3/start_in
add wave -noupdate /comb_SA_tb/DUT/B_1_3/op_in
add wave -noupdate /comb_SA_tb/DUT/B_1_3/op_out
add wave -noupdate /comb_SA_tb/DUT/B_1_3/start_out
add wave -noupdate /comb_SA_tb/DUT/B_1_3/data_out
add wave -noupdate -itemcolor Green /comb_SA_tb/DUT/B_1_3/r
add wave -noupdate /comb_SA_tb/DUT/B_1_3/r_reg
add wave -noupdate /comb_SA_tb/DUT/A_2_2/clk
add wave -noupdate /comb_SA_tb/DUT/A_2_2/rst_b
add wave -noupdate /comb_SA_tb/DUT/A_2_2/data_in
add wave -noupdate /comb_SA_tb/DUT/A_2_2/start_in
add wave -noupdate /comb_SA_tb/DUT/A_2_2/op_out
add wave -noupdate /comb_SA_tb/DUT/A_2_2/start_out
add wave -noupdate /comb_SA_tb/DUT/A_2_2/data_out
add wave -noupdate -itemcolor Magenta /comb_SA_tb/DUT/A_2_2/r
add wave -noupdate /comb_SA_tb/DUT/A_2_2/r_reg
add wave -noupdate /comb_SA_tb/DUT/B_2_3/clk
add wave -noupdate /comb_SA_tb/DUT/B_2_3/rst_b
add wave -noupdate /comb_SA_tb/DUT/B_2_3/data_in
add wave -noupdate /comb_SA_tb/DUT/B_2_3/start_in
add wave -noupdate /comb_SA_tb/DUT/B_2_3/op_in
add wave -noupdate /comb_SA_tb/DUT/B_2_3/op_out
add wave -noupdate /comb_SA_tb/DUT/B_2_3/start_out
add wave -noupdate /comb_SA_tb/DUT/B_2_3/data_out
add wave -noupdate -itemcolor Magenta /comb_SA_tb/DUT/B_2_3/r
add wave -noupdate /comb_SA_tb/DUT/B_2_3/r_reg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {155054 ps} 0} {{Cursor 2} {194945 ps} 0} {{Cursor 3} {270113 ps} 0} {{Cursor 4} {319944 ps} 0} {{Cursor 5} {394999 ps} 0} {{Cursor 6} {434910 ps} 0}
quietly wave cursor active 6
configure wave -namecolwidth 289
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {331471 ps} {448529 ps}
bookmark add wave bookmark0 {{888795 ps} {1005853 ps}} 0
