######################################################################
#
# File name : gf2mz_top_tb_compile.do
# Created on: Sun Nov 10 17:21:55 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim_10.5\\win64\\vlib modelsim_lib/work
D:\\modelsim_10.5\\win64\\vlib modelsim_lib/msim

D:\\modelsim_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../Improve-I.srcs/sources_1/new" \
"../../../../Improve-I.srcs/sources_1/new/gf2m_mul.v" \
"../../../../Improve-I.srcs/sources_1/new/gf2mz_top.v" \
"../../../../Improve-I.srcs/sources_1/new/mem_dp.v" \
"../../../../Improve-I.srcs/sources_1/new/mem_sp.v" \
"../../../../Improve-I.srcs/sources_1/new/mul_ctrl.v" \
"../../../../Improve-I.srcs/sources_1/new/gf2mz_top_tb.v" \


# compile glbl module
D:\\modelsim_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

