######################################################################
#
# File name : gf2mz_top_tb.udo
# Created on: Mon Nov 04 15:52:02 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
