######################################################################
#
# File name : decrypt_top_tb.udo
# Created on: Wed Dec 30 12:17:28 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
delete wave *
do {wave.do}