######################################################################
#
# File name : decrypt_top_tb_wave.do
# Created on: Wed Dec 30 12:17:28 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
