######################################################################
#
# File name : decrypt_top_tb_wave.do
# Created on: Fri Sep 18 10:31:18 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
