######################################################################
#
# File name : decrypt_top_tb.udo
# Created on: Fri Sep 18 10:31:18 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
delete wave *
do {wave.do}