######################################################################
#
# File name : decrypt_top_tb_compile.do
# Created on: Tue Sep 22 10:33:45 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../Verilog" \
"../../../../Verilog/S1S2_gen.v" \
"../../../../Verilog/gf2m_mul.v" \
"../../../../Verilog/clog2.v" \
"../../../../Verilog/mul_ctrl.v" \
"../../../../Verilog/gf2mz_top.v" \
"../../../../Verilog/mem_dp.v" \
"../../../../Verilog/define.v" \
"../../../../Verilog/decrypt_top.v" \
"../../../../Verilog/ctrl_top.v" \
"../../../../Verilog/mem_sp.v" \
"../../../../Verilog/gs_elim_ctrl-fat.v" \
"../../../../Verilog/comb_SA.v" \
"../../../../Verilog/gs_elim_top.v" \
"../../../../Verilog/node.v" \
"../../../../Verilog/padder.v" \
"../../../../Verilog/keccak.v" \
"../../../../Verilog/padder1.v" \
"../../../../Verilog/rconst.v" \
"../../../../Verilog/round.v" \
"../../../../Verilog/f_permutation.v" \
"../../../../Verilog/gf2mz_top_tb.v" \
"../../../../Verilog/S1S2_gen_tb.v" \
"../../../../Verilog/decrypt_top_tb.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

