######################################################################
#
# File name : GF2m_mul_digit_penta_tb_wave.do
# Created on: Sun Nov 29 20:13:15 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
