######################################################################
#
# File name : GF2m_mul_digit_penta_tb_compile.do
# Created on: Sun Nov 29 20:13:12 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../GF2m_multiplier.srcs/sources_1/new" \
"../../../../GF2m_multiplier.srcs/sources_1/new/clog2.v" \
"../../../../GF2m_multiplier.srcs/sources_1/new/GF2m_mul_digit_tb.v" \
"../../../../GF2m_multiplier.srcs/sources_1/new/GF2m_mul_digit_penta_tb.v" \
"../../../../GF2m_multiplier.srcs/sources_1/new/GF2m_mul_digit_penta.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

