######################################################################
#
# File name : GF2m_mul_digit_tb_simulate.do
# Created on: Wed Aug 28 18:39:53 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.GF2m_mul_digit_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {GF2m_mul_digit_tb_wave.do}

view wave
view structure
view signals

do {GF2m_mul_digit_tb.udo}

run 1000ns
