######################################################################
#
# File name : GF2m_mul_digit_tb.udo
# Created on: Mon Aug 26 19:17:22 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
