######################################################################
#
# File name : GF2m_mul_digit_tb.udo
# Created on: Wed Nov 25 20:14:57 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
