######################################################################
#
# File name : GF2m_mul_digit_penta_tb_wave.do
# Created on: Thu Aug 29 18:50:48 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
