######################################################################
#
# File name : GF2m_mul_digit_penta_tb_compile.do
# Created on: Thu Sep 19 00:11:26 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../GF2m_multiplier.srcs/sources_1/new/GF2m_mul_digit_penta.v" \
"../../../../GF2m_multiplier.srcs/sources_1/new/GF2m_mul_digit_penta_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

