######################################################################
#
# File name : gf2mz_top_tb_compile.do
# Created on: Wed Sep 09 15:07:01 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/work
F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim

F:\\modelsim64_10.1c\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\modelsim64_10.1c\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../Verilog" \
"../../../../Verilog/gf2m_mul.v" \
"../../../../Verilog/gf2mz_top.v" \
"../../../../Verilog/mem_dp.v" \
"../../../../Verilog/mem_sp.v" \
"../../../../Verilog/mul_ctrl.v" \
"../../../../Verilog/gf2mz_top_tb.v" \


# compile glbl module
F:\\modelsim64_10.1c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

