######################################################################
#
# File name : gf2mz_top_tb_wave.do
# Created on: Wed Sep 09 14:58:16 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
