######################################################################
#
# File name : gf2mz_top_tb.udo
# Created on: Wed Sep 09 14:58:16 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
