######################################################################
#
# File name : prng_tb_wave.do
# Created on: Mon Jan 20 11:26:10 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
