######################################################################
#
# File name : prng_tb_simulate.do
# Created on: Tue Jan 21 13:04:47 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.prng_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {prng_tb_wave.do}

view wave
view structure
view signals

do {prng_tb.udo}

run 1000ns
